# Region mapping prep
region_mapping = {
    # Europe
    "Germany": "Europe",
    "Poland": "Europe",
    "United Kingdom": "Europe",
    "France": "Europe",
    "Netherlands": "Europe",
    "Greece": "Europe",
    "Hungary": "Europe",
    "Ireland": "Europe",
    "Switzerland": "Europe",
    "Spain": "Europe",
    "Estonia": "Europe",
    "Malta": "Europe",
    "Denmark": "Europe",
    "Austria": "Europe",
    "Italy": "Europe",
    "Belgium": "Europe",
    "Lithuania": "Europe",
    "Portugal": "Europe",
    "Serbia": "Europe",
    "Czech Republic": "Europe",
    "Slovakia": "Europe",
    "Finland": "Europe",
    "Ukraine": "Europe",
    "Croatia": "Europe",
    "Slovenia": "Europe",
    "Luxembourg": "Europe",
    "Belarus": "Europe",
    "Moldova": "Europe",
    # Asia
    "Israel": "Asia",
    "Kazakhstan": "Asia",
    "Armenia": "Asia",
    "Singapore": "Asia",
    "Taiwan": "Asia",
    "Azerbaijan": "Asia",
    "Malaysia": "Asia",
    "Viet Nam": "Asia",
    "Hong Kong": "Asia",
    # Americas
    "United States": "Americas",
    "Chile": "Americas",
    "Colombia": "Americas",
    "Mexico": "Americas",
    "Canada": "Americas",
    "Brazil": "Americas",
    "Argentina": "Americas",
    "Costa Rica": "Americas",
    # Africa
    "Egypt": "Africa",
    "South Africa": "Africa",
    # Oceania
    "Australia": "Oceania",
    "New Zealand": "Oceania",
    # Other
    "Japan": "Asia",
    "South Korea": "Asia",
    "Iceland": "Europe",
    "Lebanon": "Asia",
    "Georgia": "Asia",
    "Sweden": "Europe",
    "Denmark": "Europe",
    "Luxembourg": "Europe",
    "nan": "Unknown"  # For missing data
}